# kind-config.yaml
# Kind cluster configuration for local Kubernetes development
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    image: kindest/node:v1.29.0
    kubeadmConfigPatches:
      - |
        kind: InitConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "ingress-ready=true"
    extraPortMappings:
      - containerPort: 80
        hostPort: 30000
        protocol: TCP
      - containerPort: 443
        hostPort: 30001
        protocol: TCP
  - role: worker
    image: kindest/node:v1.29.0
