---
apiVersion: v1
kind: Namespace
metadata:
  name: stock-ticker

---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: stock-ticker
  name: stock-ticker
spec:
  selector:
    matchLabels:
      app: stock-ticker
  template:
    metadata:
      labels:
        app: stock-ticker
    spec:
      containers:
      - name: stock-ticker
        image: dann7387/ping-identity-sre-interview-exercise:latest
        imagePullPolicy: Always
        env:
          - name: SYMBOL
            valueFrom:
              configMapKeyRef:
                name: stock-ticker-config
                key: symbol
          - name: NDAYS
            valueFrom:
              configMapKeyRef:
                name: stock-ticker-config
                key: ndays
          - name: APIKEY
            valueFrom:
              secretKeyRef:
                name: stock-ticker-secret
                key: apikey

---
apiVersion: v1
kind: Service
metadata:
  namespace: stock-ticker
  name: stock-ticker
spec:
  selector:
    app: stock-ticker
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: stock-ticker
  name: stock-ticker-ingress
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: stock-ticker
                port:
                  number: 80

---
apiVersion: v1
kind: Secret
metadata:
  namespace: stock-ticker
  name: stock-ticker-secret
type: Opaque
data:
  apikey: "QzIyN1dEOVczTFVWS1ZWOQ=="

---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: stock-ticker
  name: stock-ticker-config
data:
  symbol: MSFT
  ndays: "7"

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  namespace: stock-ticker
  name: stock-ticker-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: stock-ticker
  minReplicas: 2
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  namespace: stock-ticker
  name: stock-ticker-pdb
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: stock-ticker